---
- name: Install Grafana repository
  yum_repository:
    name: grafana
    description: Grafana repo
    baseurl: https://packagecloud.io/grafana/stable/el/$releasever/$basearch
    gpgcakey: https://packagecloud.io/gpg.key
    gpgkey: https://grafanarel.s3.amazonaws.com/RPM-GPG-KEY-grafana
    gpgcheck: yes

- name: Install InfluxDB repository
  yum_repository:
    name: influxdb
    description: InfluxDB repo
    baseurl: https://repos.influxdata.com/rhel/\$releasever/\$basearch/stable
    gpgkey: https://repos.influxdata.com/influxdb.key
    gpgcheck: yes

- name: Install Grafana package
  yum:
    name: "{{ grafana_pkg }}"
    state: present
  notify:
    - Restart grafana

- name: Install InfluxDB package
  yum:
    name: "influxdb"
    state: present

- name: Configure Grafana
  template:
    src: grafana.ini.j2
    dest: /etc/grafana/grafana.ini
  tags:
    - grafana_config

- name: Configure InfluxDB
  template:
    src: influxdb.conf.j2
    dest: /etc/influxdb/influxdb.conf
  tags:
    - influx_config

- name: Configure Grafana LDAP
  template:
    src: ldap.toml.j2
    dest: /etc/grafana/ldap.toml
  notify:
    - Restart grafana
  tags:
    - grafana_config

- name: Make sure Grafana is enabled and running
  service:
    name: grafana-server
    enabled: yes
    state: started

- name: Make sure InfluxDB is enabled and running
  service:
    name: influxdb
    enabled: yes
    state: started
